twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']

    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/public/css' : styles

when@test:
    twig:
        strict_variables: true
